name: Build (Keycloak)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'keycloak/**'

jobs:
  keycloak:
    name: Build Optimized Keycloak Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Read environment variables
        uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: keycloak/env

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/blevinn/keycloak-optimized
          tags: |
            type=semver,pattern={{version}},value=${{env.KEYCLOAK_VERSION}}
            type=semver,pattern={{major}}.{{minor}},value=${{env.KEYCLOAK_VERSION}}
            type=semver,pattern={{major}},value=${{env.KEYCLOAK_VERSION}}
          labels: org.opencontainers.image.source=https://github.com/blevinn/kube-containers

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.KEYCLOAK_VERSION }}
          platforms: linux/amd64,linux/arm64

